syntax = "proto3";

package message;

message LoginReq{
    int32 uid = 1;
    string token= 2;
}

message LoginRsp {
    int32 error = 1;
    int32 uid = 2;
    string token = 3;
}

service StatusService {
    rpc Login (LoginReq) returns (LoginRsp) {}
}

message AddFriendReq{
    int32  apply_uid = 1;
	string name = 2;
	string description = 3;
	string icon = 4;
	string nickname = 5;
	int32  sex = 6;
	int32  to_uid = 7;
}

message AddFriendRsp {
	int32 error = 1;
	int32 apply_uid = 2;
	int32 to_uid = 3;
}

message ReplyFriendReq {
	int32 reply_uid = 1;
	bool  agree = 2;
	int32 to_uid = 3;
}

message ReplyFriendRsp {
	int32 error = 1;
	int32 reply_uid = 2;
	int32 to_uid = 3;
}

message SendChatMsgReq{
	int32 from_uid = 1;
	int32 to_uid = 2;
	string message = 3;
}

message SendChatMsgRsp{
	int32 error = 1;
	int32 from_uid = 2;
	int32 to_uid = 3;
}

message AuthFriendReq{
	int32 from_uid = 1;
	int32 to_uid = 2;
}

message AuthFriendRsp{
	int32 error = 1;
	int32 from_uid = 2;
	int32 to_uid = 3;
}

message TextChatData{
	string msg_id = 1;
	string msg_content = 2;
}

message TextChatMsgReq {
	int32 from_uid = 1;
    int32 to_uid = 2;
	repeated TextChatData text_msgs = 3;
}

message TextChatMsgRsp {
	int32 error = 1;
	int32 from_uid = 2;
	int32 to_uid = 3; 
	repeated TextChatData text_msgs = 4;
}

service ChatService {
	rpc NotifyAddFriend(AddFriendReq) returns (AddFriendRsp) {}
	rpc ReplyAddFriend(ReplyFriendReq) returns (ReplyFriendRsp) {}
	rpc SendChatMsg(SendChatMsgReq) returns (SendChatMsgRsp) {}
	rpc NotifyAuthFriend(AuthFriendReq) returns (AuthFriendRsp) {}
	rpc NotifyTextChatMsg(TextChatMsgReq) returns (TextChatMsgRsp){}
}